name: lattice
description: A Flutter Matrix client with multiple adaptive layouts.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  matrix: ^6.1.1
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^10.0.0
  dynamic_color: ^1.7.0
  animations: ^2.0.11
  sqflite_common_ffi: ^2.3.7+1
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_vodozemac: ^0.5.0
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4
  canonical_json: ^1.1.2
  vodozemac: ^0.5.0
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^18.0.1
  desktop_notifications: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
