name: lattice
description: A Flutter Matrix client with multiple adaptive layouts.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  matrix: ^6.1.1
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^10.0.0
  dynamic_color: ^1.7.0
  animations: ^2.0.11
  url_launcher: ^6.2.6
  sqflite_common_ffi: ^2.3.7+1
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
